import { triggerEvent } from "../.."
import { getCookie } from "../../../cookie"
import { AFFILIATION } from "../../constants"

export const handleWedding = (
  item: any,
  index: number,
  title: any,
  urlType: any,
  props: any,
  dataLayer: any,
  isMobile: boolean,
  eventName: string,
) => {
  triggerEvent({
    action: eventName,
    params: {
      ...dataLayer,
      index: index,
      buttonLinkName: title || "",
      link_text: title || "",
      eventType: "",
      eventName: "",
      eventPlace: "",
      eventTicketsQty: "",
      eventDate: "",
      datesToBook: "",
      package: "",
      theme: "",
      functionDate: "",
      isFlexibe: "",
      isGuestRooms: "",
      currentLocation: "",
      additionalEvent: "",
      weddingFunctionName: title || "",
      visitSource: "",
      clientId: getCookie("_ga")?.slice(6),
      brandName: AFFILIATION,
      no_of_items: props?.items?.[0]?.tabs?.length,
      outbound: urlType == "internal" ? false : true,
      widget_type: props?._type,
      widget_title: isMobile ? props?.title?.mobileTitle?.[1] : props?.title?.desktopTitle?.[0],
      item_name: title || "",
      item_type: item?._type,
      departureDate: "",
      arrivalDate: "",
      widget_description: props?.subTitle,
      noOfAdults: "",
      noOfChild: "",
      noOfRooms: "",
      offerCategory: "",
      offerCode: "",
      offerID: "",
      offerName: "",
      offerValidity: "",
      specialCode: "",
      location: "",
      pageSection: isMobile ? props?.title?.mobileTitle?.[1] : props?.title?.desktopTitle?.[0],
    },
  })
}
