export const CONSTANTS = {
  LOGIN: "login / join",
  CLOSE: "CLOSE",
  VIEW_MORE: "view more",
  VIEW: "VIEW",
  GLOBAL_SEARCH_PLACE_HOLDER: "Click here to search Destinations, Hotels, Restaurants and Holidays.",
  LOAD_MORE: "LOAD MORE",
  LOAD_LESS: "LOAD LESS",
  VIEW_MORE_CAPS: "VIEW MORE",
  VIEW_LESS: "VIEW LESS",
  VIEW_COMPARSION: "VIEW COMPARISON",
  PAGE_NOT_FOUND: "404",
  BACK_TO_HOMEPAGE: "BACK TO THE HOMEPAGE",
  VIEW_OFFERS: "View All Offers",
  MORE_TO_EXPAND_TEXT: "more",
  GUESTS: "Guests",
  ROOMS: "Rooms",
  ROOM_SMALL: "Room",
  BOOK_NOW: "BOOK NOW",
  EXPLORE: "Explore",
  MORE: "MORE",
  LESS: "LESS",
  TEXT_AREA_CHARACTER_LIMIT: 180,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  NINE: 9,
  TWELVE: 12,
  FIFTEEN: 12,
  TEN: 10,
  EIGHTEEN: 18,
  GIFT_CARD_PREVIEW: "GIFT CARD PREVIEW",
  CHANGE_CARD: "change Card",
  CITY_PLACEHOLDER: "city",
  SEARCH_PLACEHOLDER: "Search for a Restaurant or Cuisine",
  BOOKING_SEARCH_PLACEHOLDER: "Find a Hotel or Destination",
  ITEM_DESCRIPTION_CHARACTER_LIMIT: 130,
  WEB_COMMENT_DESCRIPTION_LIMIT: 230,
  MOBILE_COMMENT_DESCRIPTION_LIMIT: 125,
  ITEM_DESCRIPTION_LARGE_LIMIT: 400,
  ITEM_DESCRIPTION_MOBILE_LIMIT: 50,
  CUSTOM_DROP_DOWN_HOTEL: "Hotel",
  ENROL_NOW: "ENROL NOW",
  SUBMIT_BUTTON: "submit",
  RESULT_NOT_FOUND: "We can't find a result for your search.",
  RESULT_NOT_FOUND_DESC: "Please contact our global contact centre at 1-800-111-825 for any further assistance",
  SEARCH_RESULTS_NOT_FOUND: "There are no results for your search filter selections, please select other filters",
  MANAGE_CARDS: " MANAGE CARDS",
  COUPON_CODE_WARNING: " Please select only one room",
  COUPON_CODE_ERROR_MESSAGE: "Coupon Code is not applicable for Selected Brand",
  TRAVEL_AGENCY_ERROR_MESSAGE: "Travel Agency Code is not applicable for Selected Brand",
  CONTINUE: "continue",
  CONTINUE_TO_CONFIRM: "CONTINUE TO CONFIRM",
  CONFIRM_BOOKING: "CONFIRM BOOKING",
  MEMBERSHIP_TYPE: "mebershiplabel",
  ACCORDION_TITLE_TEXT: "ADDONS",
  DYNAMIC: "Dynamic",
  STATIC: "Static",
  PAYMENT: "PAYMENT",
  RESEND_OTP: "RESEND OTP",
  VIEW_MORE_RATES: "VIEW MORE RATES",
  VIEW_LESS_RATES: "VIEW LESS RATES",
  VIEW_MORE_PACKAGES: "VIEW MORE PACKAGES",
  VIEW_LESS_PACKAGES: "VIEW LESS PACKAGES",
  NOT_SELECTED: "Not selected",
  CURRENT_BOOKED_ROOM: "Current Booked Room",
  NEW_SELECTED_ROOM: "New Selected Room",
  RESERVATION: "RESERVATION",
  ROOM: "ROOM",
  CONFIRM: "CONFIRM",
  PROCEED: "PROCEED",
  CONFIRM_CHANGE: "CONFIRM CHANGE",
  CONFIRM_DELETE: "CONFIRM DELETE",
  VIEW_HOTEL: "VIEW HOTEL",
  PRICE_CHANGE: "Price Change",
  DEAR: "Dear",
  SENDER: "Sender",
  MANDATORY_FIELDS: "*Please fill all mandatory fields",
  VIEW_LESS_TEXT: "less",
  CHECK_BOX_LABEL: "I have read the ",
  ADD: "ADD",
  SPECIAL_CODE: "Special Code",
  SEARCH: " SEARCH",
  ACCOUNT: "ACCOUNT",
  LOGIN_JOIN: "LOGIN / JOIN",
  TERMS_AND_CONDITIONS: "terms and conditions",
  BROCHURE: "BROCHURE",
  DIALOG: "dialog",
  VARIANT_LINK_TYPE: "link",
  START_DATE: "start date",
  MY_ACCOUNT_EMPTY_TEXT: "there are no gift cards registered under your account.",
  BOOKED_ON: "BOOKED ON",
  EXPIRY_DATE: "EXPIRY DATE",
  EXPIRE_BY: "EXPIRE BY",
  RECEIVED_FROM: "RECEIVED FROM",
  BALANCE: "Balance",
  MANAGE_CARD: " MANAGE CARD",
  VIEW_ALL: " VIEW ALL",
  SAVE: "SAVE",
  CANCEL: "CANCEL",
  SELECT_CARD: "SELECT CARD",
  PAY_NOW: "PAY NOW",
  DEBIT_CARD: "DEBIT CARD",
  CREDIT_CARD: "CREDIT CARD",
  NET_BANKING: "NETBANKING",
  SEARCH_FIELD: "searchField",
  DROP_DOWN: "dropDown",
  PURCHASE_ORDER_NUMBER: "PURCHASE ORDER NUMBER",
  TAX: "TAX",
  FINAL_AMOUNT_PAID: "FINAL AMOUNT PAID",
  AMOUNT: "AMOUNT",
  COPY: "COPY",
  ALL_PHOTOS_VIDEOS: "All PHOTOS & VIDEOS",
  GALLERY: "GALLERY",
  DESTINATION: "Destination",
  CLAIM_MISSING_POINTS: "CLAIM MISSING POINTS",
  BACK_TO_TXN_SUMMARY: "BACK TO TRANSACTION SUMMARY",
  DATE: "DATE",
  TRANSACTION_DETAIL: "TRANSACTION DETAIL",
  AMOUNT_SPENT: "AMOUNT SPENT",
  DISCOUNTS: "DISCOUNTS",
  NEUCOINS_EARNED: "NEUCOINS EARNED",
  SORTING_BY_DATE: "Sorting by Date",
  SELECT_PACKAGE: "Select Package*",
  SOMEONE_ELSE: "SOMEONE ELSE",
  MYSELF: "MYSELF",
  PURCHASE_TEXT: "This purchase is for",
  ADULTS: "Adults",
  ADULT: "Adult",
  CHILD: "Child",
  CHILDREN: "Children",
  CHECK_RATES: " Check rates",
  SPECIAL_OFFER: "Special Offer",
  RESERVE_A_TABLE: "RESERVE A TABLE",
  SEVEN: 7,
  ADD_MORE_ROOMS: "ADD MORE ROOMS",
  NEED_6_ROOMS_OR_MORE: " Need 6 rooms or more? ",
  WEBSITE: "reservations@tajhotels.com",
  ADDRESS: "address",
  TEXT: "Text",
  GIFT_CARD_PURCHASE: "GIFT_CARD_PURCHASE",
  FORM_DESCRIPTION_CHARACTER_LIMIT: 120,
  PRICE: "price",
  SPECIAL_TITLE: "specialTitle",
  PROPERTY_DATA_DESCRIPTION_LIMIT: 220,
  REFRESH_THIS_PAGE: "REFRESH THIS PAGE",
  UNSTABLE_CONNECTION: "UNSTABLE CONNECTION DETECTED",
  CHECK_YOUR_INTERNET: "Please check your internet connection and try again.",
  EIGHT: 8,
  EDIT: "EDIT",
  CONTINUE_2: "CONTINUE",
  I_HAVE_READ_AND_AGREE_TO: "I have read and agree to",
  TERMS_CONDITIONS: "Terms & Conditions",
  Balance_Amount: "Balance Amount",
  Balance_Expiry_Date: "Expiry Date",
  EPICURE: "EPICURE",
  VOUCHER_NUMBER: "VOUCHER NUMBER",
  VOUCHER_PIN: "VOUCHER PIN",
  STATUS: "STATUS",
  VALID_UNIT: "VALID UNTIL",
  AVAILABLE: "AVAILABLE",
  CHECK_RATES_1: "CHECK RATES",
  TOOL_TIP_TEXT_EPICURE: "Epicure membership valid only in India",
  TOOL_TIP_TEXT_GIFTCARD: "Taj Experience Gift Cards are deliverable only in India",
  ROOM_UNAVAILABLE:
    "There are no rooms available matching your search criteria. Please try selecting alternate dates, modifying your search options, or choosing an alternate property.",
  OTHER_HOTELS_DESCRIPTION:
    "There are no rooms available matching your search criteria. Please modify your search options or choose an alternate hotel from the below list.",
  TOOL_TIP_TEXT: "This modification period has expired, please contact the property to discuss changes",
  COMPLEMENTARY_TOOL_TIP: "This reservation can only be modified once",
  BOOKING_ERROR_TEXT: "We could not book your room. Please try again.",
  INVENTORY_ROOMS_NOT_AVAILABLE: "Please select another room to continue.",
  DOWNLOAD_FACTSHEET_ERROR: "Please select any hotel to download",
  ROOM_NOT_AVAILABLE: "THE SELECTED ROOM IS UNAVAILABLE",
  INVALID_COUPON_CODE: "INVALID COUPON CODE",
  COUPON_CODE_ERROR: "COUPON CODE ERROR",
  COUPON_CODE_APPLIED_SUCCESSFULL:
    "Note: The applicable coupon discount will be displayed at the time of selecting the payment method.",
  PHYSICAL_GIFT_CARD: "Physical Gift Card",
  E_GIFT_CARD: "E-Gift Card",
  SHARE: "SHARE",
  PRINT: "PRINT",
  OFFER: "OFFER",
  PAYMENT_INIT_ERROR: "We are currently unable to process your request",
  INCLUSIVE_TAXES: "*Inclusive of all Taxes",
  SEE_MORE: "SEE MORE",
  HOTELS: "HOTELS",
  DESTINATIONS: "DESTINATIONS",
  MEMBER_RATE: "MEMBER RATE",
  YOUR_MEMBER_RATE: "YOUR MEMBER RATE",
  SELECT: "SELECT",
  STANDARD_RATE: "STANDARD RATE",
  REDEEM_VOUCHER: "REDEEM VOUCHER",
  ROOM_LABEL: "Room",
  NIGHT_LABEL: "Night",
  HOTELS_IN: "Hotels in",
  NEU_COINS: "NeuCoins",
  NEU_COIN: "NeuCoin",
  TOTAL_PRICE_CHANGE: "Total Price Change",
  TOTAL_AMOUNT: "Total Amount",
  AMOUNT_AT_HOTEL: "Total Amount Payable at Hotel",
  TOTAL_TO_PAY: "Total To Pay",
  TE_GIFT_CARD: "Gift Card Redemption",
  TE_GIFT_CARD_REDEEMED: "Gift Card/s Redeemed",
  COUPON_DISCOUNT: "Coupon Discount",
  MEMBERSHIP_LABEL: "Membership :",
  // PDF file names
  GIFT_CARD_PDF: "Taj Experience Gift Card Confirmation",
  UPCOMING_BOOKINGS_PDF: "Upcoming_Booking",
  GIFT_CARD_RELOAD: "Taj Experience Gift Card Reload Confirmation",
  GIFT_CARD_EMAIL: "Woohoo - Your order is placed!",
  STATUS_TYPES: {
    CONFIRMED: "confirmed",
  },
  EXCLUSIVE_RATE: "EXCLUSIVE RATE",
  NO_RESULTS: "No Results Found For Your Search",
  PHONE_KEY: "Phone",
  PAYABLE_AMOUNT: "Payable Amount",
  CONFIRM_AND_PAY: "CONFIRM AND PAY",
  INDIA: "IN",
  REDEEMED: "Redeemed",
  BACK_BUTTON_CLICKED: "BACK_CLICKED",
  TAJ_LOGO_CLICKED: "LOGO_CLICKED",
  LOGIN_OR_MY_ACCOUNT_CLICKED: "LOGIN_CLICKED",
  CARD: "card",
  COMPARISON_TABLE: "comparisonTable",
  DOWNLOAD_LOWER_CASE: "download",
  PRINT_LOWER_CASE: "print",
  EPICURE_PRIVILEGED: "Privileged",
  EPICURE_PREFERRED: "Preferred",
  EPICURE_BANK: "corporate",
  EMPTY_SEARCH_RESULTS: "There are no results found for your search.",
  WEB_TYPE: "WEB",
  MOBILE_TYPE: "MOBILE",
}

export const HOTEL_NAVIGATION_TABS = [
  {
    key: "rooms_and_suites",
    value: "ROOMS & SUITES",
    url: "/rooms-and-suites",
    type: "internal",
  },
  { key: "overview", value: "OVERVIEW", url: "/", type: "internal" },
  {
    key: "offers_and_promotions",
    value: "OFFERS",
    url: "/offers-and-promotions",
    type: "internal",
  },
  {
    key: "restaurants",
    value: "DINING",
    url: "/restaurants",
    type: "internal",
  },
  {
    key: "meetings_and_event_venues",
    value: "VENUES",
    url: "/meetings-and-event-venues",
    type: "internal",
  },
  {
    key: "j_wellness_circle",
    value: "WELLNESS",
    url: "/j-wellness-circle",
    type: "internal",
  },
  { key: "wellness", value: "WELLNESS", url: "/wellness", type: "internal" },
  {
    key: "experiences",
    value: "EXPERIENCES",
    url: "/experiences",
    type: "internal",
  },
  { key: "gallery", value: "GALLERY", url: "/gallery", type: "internal" },
  {
    key: "places_to_visit",
    value: "ATTRACTIONS",
    url: "/places-to-visit",
    type: "internal",
  },
  {
    key: "gift_hamper_festive",
    value: "GIFT HAMPER",
    url: "/gift-hamper-festive",
    type: "internal",
  },
  {
    key: "niu_and_nau",
    value: "NIU & NAU",
    url: "/niu-and-nau",
    type: "internal",
  },
]

export const DESTINATION_NAVIGATION_TABS = [
  {
    key: "hotels",
    value: "HOTELS",
    url: "/hotels",
    type: "internal",
  },
  {
    key: "highlights",
    value: "HIGHLIGHTS",
    url: "/about",
    type: "internal",
  },
  {
    key: "restaurants",
    value: "DINING",
    url: "/restaurants",
    type: "internal",
  },
  {
    key: "experiences",
    value: "EXPERIENCES",
    url: "/experiences",
    type: "internal",
  },
  {
    key: "spa",
    value: "SPAS",
    url: "/spa",
    type: "internal",
  },
  {
    key: "holiday_packages",
    value: "HOLIDAYS",
    url: "/holiday-packages",
    type: "internal",
  },
]

export const LOGIN_CONSTANTS = {
  LOGIN_TITLE: "LOGIN / JOIN",
  LOGIN: "Login",
  NUE_PASS_LOGO: "/nuepass-logo.svg",
  NUE_PASS_TITLE: "NEUPASS MEMBER BENEFITS",
  PASSWORD: "Password",
  RememberMe: "Remember me",
  PASSWORD_SUB_TITLE: "Enter password for TIC / NeuPass Number ",
  OTP_INVALID_ERROR: "Entered wrong otp.",
  OTP_FAILED_ERROR: "Something went wrong, Please try again later.",
  OTP_LIMIT_ERROR: "OTP limit reached Please try again after 5 minutes",
}

export const OTP_FIELDS_LENGTH = 6
export const CART_SUMMARY = "CART SUMMARY"

export const SEARCH_CARD_CONSTANTS = {
  CUISINE: "Cuisine",
  DRESS_CODE: "Dress Code",
  TIMINGS: "Timings",
  TIMING: "Timing",
  LUNCH: "Lunch",
  DINNER: "Dinner",
  BOOK_NOW: "BOOK NOW",
  SOLD_OUT: "SOLD OUT",
  RESERVE_NOW: "RESERVE NOW",
  VIEW_PACKAGES: "VIEW PACKAGES",
}

//my account constants

export const OVER_VIEW_GIFT_CARDS = "There are no gift cards registered under your account."
export const OVER_VIEW_MEMBERSHIP = "There are no membership's registered under your account."
export const OVER_VIEW_OFFERS = "There are no Offers & benefits under your account."
export const OVER_VIEW_VOUCHERS = "There are no vouchers under your account."
export const OVER_VIEW_FILTER_VOUCHERS = "There are no vouchers under your account with these filters."
export const NO_ORDERS_AVAILABLE = "There are no bookings under your account."
export const NO_UPCOMING_ORDERS = "NO UPCOMING ORDERS AVAILABLE."
export const NO_PAST_ORDERS = "NO PAST ORDERS AVAILABLE."
export const ENTER_ADDRESS = "ENTER YOUR ADDRESS"
export const SEARCH_ADDRESS = "SEARCH YOUR ADDRESS"
export const ADDRESS = "Address"
export const DEFAULT_ADDRESS = "Default Address"
export const ADD_ADDRESS = "ADD NEW ADDRESS"
export const SET_DEFAULT_ADDRESS = "SET AS DEFAULT ADDRESS"
export const CONFIRM_DELETE_ADDRESS = "Confirm Delete Address?"
export const CONFIRM_DELETE_ADDRESS_TEXT = "Are you sure to delete this address?"

// Icons
export const ICONS = {
  CHECK_MARK: "/en-in/CheckMark.png",
  HAMBURGER_ICON: "/en-in/hamburger.png",
  HAMBURGER_GOLD_ICON: "/en-in/hamburger_gold.svg",
  BACK_ARROW_BUTTON: "/en-in/back-Arrow-Icon.png",
  SEARCH_ICON: "/en-in/search-icon.png",
  OFFERS_ICON: "/en-in/offers-icon.png",
  BUTTON_TICK_ICON: "/en-in/button-tick.png",
  CALENDER_ICON: "/en-in/CalendarIcon.png",
  CALENDER_SVG: "/en-in/CalendarIcon.svg",
  ACCOUNT_CALENDER_ICON: "/en-in/account-calender-icon.svg",
  CLOSE_GOLD_ICON: "/en-in/close-gold.svg",
  BUSINESS_SERVICE_SEARCH_ICON: "/en-in/business-service-search-icon.png",
  MODAL_CLOSE_ICON: "/en-in/modal-close.png",
  QUOTE_ICON: "/en-in/quotation-mask.png",
  WARNING_ICON: "/en-in/warning-logo.svg",
  COMMON_ICON: "/en-in/common-search.png",
  Star_ICON: "/en-in/Star.png",
  TAJ_GOLD_LOGO: "/en-in/taj-gold-logo.svg",
  SEARCH_FIELD_CLOSE_ICON: "/en-in/close-icon.svg",
  GUEST_COUNT_ICON: "/en-in/members.svg",
  BLACK_MARKER_MAP_ICON: `https://cdn.sanity.io/images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/${process.env.NEXT_PUBLIC_SANITY_DATASET}/94a5bd1fe6e44da40c6eb6d6ac52cf1c843cc193-17x24.svg`,
  MARKER_MAP_ICON: `https://cdn.sanity.io/images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/${process.env.NEXT_PUBLIC_SANITY_DATASET}/ecae61d9e0123c9ab3b80db7cc75c54fa3309a2a-24x34.png`,
  MARKER_TAJ_MAP_ICON: `https://cdn.sanity.io/images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/${process.env.NEXT_PUBLIC_SANITY_DATASET}/7fbe035ec0985cc4ac2ce9e75b2ffba022d20ca5-67x95.svg`,
  SUCCESS_TICK: "/en-in/success-tick.svg",
  BUTTON_GRAY_TICK: `https://cdn.sanity.io/images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/${process.env.NEXT_PUBLIC_SANITY_DATASET}/e99da18e92cb79588c7a7055398b30a1629dbb0a-24x23.png`,
  MAIL_ICON: "/en-in/email.svg",
  UPLOAD_CLOUD_ICON: "/en-in/upload-cloud-icon.svg",
  DOCUMENT_ICON: "/en-in/document-icon.svg",
  NO_INTERNET_ICON: "/en-in/no-internet.png",
  GLOBAL_SEARCH_ICON: "/en-in/Search-Icon.svg",
  GLOBAL_SEARCH_MIC_ICON: "/en-in/Mic-Icon.svg",
  NOT_DELIVERED: "/en-in/not-delivered.svg",
  GOLDEN_IN_PROGRESS: "/en-in/golden-in-progress.svg",
  GOLDEN_DONE: "/en-in/golden-done.svg",
  TAJ_LOADER: "/en-in/taj_loader.gif",
  SELECTED_ICON: "/en-in/selected-icon.svg",
  TRANSPARENT_ARROW_LEFT: "/en-in/transparent-arrow-left.svg",
  TRANSPARENT_ARROW_RIGHT: "/en-in/transparent-arrow-right.svg",
  PREV_GOLD_COLOR_ARROW: "/en-in/taj-gold-left-arrow.svg",
  NEXT_GOLD_COLOR_ARROW: "/en-in/taj-gold-right-arrow.svg",
  SHARE_CLOSE_ICON: "/en-in/close.svg",
  SHARE_MESSENGER_ICON: "/en-in/share-messenger.svg",
  SHARE_MAIL_ICON: "/en-in/share-mail.svg",
  SHARE_WHATSAPP_ICON: "/en-in/share-whatsapp.svg",
  SHARE_DOWNLOAD_ICON: "/en-in/share-download.svg",
  PLUS_ICON: "/en-in/plus-icon.svg",
  MINUS_ICON: "/en-in/minus-icon.svg",
  SEARCH_ICON_2: "/en-in/Search-Icon.svg",
  SEARCH_ICON_WHITE: "/en-in/search-icon-white.svg",
  CLOCK: "/en-in/Clock.svg",
  SUCCESS_TICK_ICON: "/en-in/success-circle-tick.svg",
  LEFT_ARROW: "/en-in/left-arrow.svg",
  UP_ARROW: "/en-in/up-arrow.png",
  GOLD_PRINT_ICON: "/en-in/print-icon-color.svg",
  GOLD_MAIL_SHARE_ICON: "/en-in/share_icon.svg",
  PLAY_STORE: "/en-in/play-store-button.png",
  APP_STORE: "/en-in/app-store-button.png",
  SCROLL_DOWN: "/en-in/scroll-down.png",
  MIC_ICON: "/en-in/Sound.png",
  BANNER_SCROLL_DOWN: "/en-in/scroll-down-arrow-2.png",
  DOWN_ARROW: "/en-in/DownArrow.png",
  ROOM_DETAILS: "/en-in/room-details-img.png",
  CLOSE_WHITE_ICON: "/en-in/white_close_icon.svg",
  CLOSE_BLACK_ICON: "/en-in/close-icon.svg",
  CONFIRMATION_MAIL_SHARE_ICON: "/en-in/mail-icon.svg",
  GOLD_COINS_ICON: "/en-in/coins.png",
  HOTEL_BANNER: "/en-in/Hero.png",
  PHONE_ICON: "/en-in/phone.svg",
  KEY_ARROW_DOWN: "/en-in/arrow-down.svg",
  SVG_TICK_MARK: "/en-in/Tick_mark_svg.svg",
  MORE_ICON: "/en-in/more.svg",
  WHITE_DOWNLOAD_ICON: "/en-in/white-download-icon.png",
  TAJ_FAVICON: "/en-in/TAJ_favicon.svg",
  GOLD_DOWNLOAD_ICON: `https://cdn.sanity.io/images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/${process.env.NEXT_PUBLIC_SANITY_DATASET}/7ac06d18532e980221f7bcb3bbb300029ed9d900-20x20.png`,
  VOUCHER_IMAGE: "image-7efb0e0bd36eed2f9d7eb710aacf8b448669eaaf-360x352-jpg",
  DROP_DOWN_ICON: "/en-in/drop-down-arrow.svg",
  SORT_ICON: "/en-in/Sort.svg",
  USER_PROFILE: "/en-in/user_profile.svg",
  GOLDEN_DOWN_ARROW: "/en-in/golden-down-arrow.svg",
  GOLDEN_UPWARD_ARROW: "/en-in/golden-upward-arrow.svg",
}

export const MANIFEST_FILE_PATH = "/en-in/manifest.json"

export const externalNavigation: any = {
  TAJ: "",
  GINGER: process.env.NEXT_PUBLIC_GINGER_URL,
  AMA: process.env.NEXT_PUBLIC_AMA_URL,
  SELEQTIONS: process.env.NEXT_PUBLIC_SELEQTIONS_URL,
  VIVANTA: process.env.NEXT_PUBLIC_VIVANTA_URL,
}

export const BREADCRUMB_CONSTANTS: any = {
  ROOMS_AND_SUITES: "Rooms",
  RESTAURANTS: "Restaurants",
  OFFERS_AND_PROMOTIONS: "Offers",
  MEETINGS_AND_EVENT_VENUES: "Event Venues",
  WELLNESS: "Wellness",
  J_WELLNESS_CIRCLE: "J Wellness Circle",
  PLACES_TO_VISIT: "Attractions",
  THECHAMBERS: "The Chambers",
}

export const MULTI_PACKAGE_OFFERTYPE = "multiplePackages"
export const SINGLE_PACKAGE_OFFERTYPE = "singlePackage"
export const SEB_PACKAGE_OFFERTYPE = "specialEmployeeBenefitPackages"
export const GINGER_BRAND_NAME = "Ginger"
export const SELEQTIONS_BRAND_NAME = "Seleqtions"
export const VIVANTA_BRAND_NAME = "Vivanta"
export const TAJ_BRAND_NAME = "Taj"
export const brandsToShowPrices = [
  SELEQTIONS_BRAND_NAME?.toLowerCase(),
  VIVANTA_BRAND_NAME?.toLowerCase(),
  TAJ_BRAND_NAME?.toLowerCase(),
]
export const BRANDS_ORDER_SEQUENCE = ["Taj", "Seleqtions", "Vivanta", GINGER_BRAND_NAME, "Ama"]

export const CorporateAccessCugType = "corporate"
export const TravelAgencyCugType = "travel"
export const CouponCugType = "coupon"
export const VoucherCugType = "voucher"

export const CONTENT_TYPE = {
  HOTELS: "Hotels",
  PALACES: "Palaces",
  RESORTS: "Resorts",
  SAFARIS: "Safaris",
  HOTEL_ROOMS: "hotelRooms",
  HOTEL_HOLIDAYS: "hotelHolidays",
  ALL_IHCL_HOTELS: "allIHCLHotels",
  NON_IHCL_HOTELS: "NonIHCLHotels",
  NON_IHCL_SAFARIS: "NonIHCLSafaris",
  NON_IHCL_PALACES: "NonIHCLPalaces",
  NON_IHCL_RESORTS: "NonIHCLResorts",
  NEW_TAJ_OPENINGS: "newTajOpenings",
  OPENING_SOON_TAJ: "openingSoonTaj",
  HOTEL_ATTRACTIONS: "hotelAttractions",
  BRAND_RESTAURANTS: "brandRestaurants",
  HOTEL_EXPERIENCES: "hotelExperiences",
  OPENING_SOON_NON_TAJ: "openingSoonNonTaj",
  RESTAURANT_OVERVIEW: "restaurantOverview",
  NEW_NON_TAJ_OPENINGS: "newNonTajOpenings",
  HOTEL_SIGNATURE_DINING: "hotelSignatureDining",
  WEDDING_VENUES: "weddingVenues", //wedding page
  HAMPERS: "hampers", //static hampers landing page
  ALL_EVENTS_VENUES: "allEventVenues", //meetings page
  HOTEL_EVENT_VENUES: "hotelEventVenues", // hotel specific venues
}
