//local storage constants
export const DOB = global?.localStorage?.getItem("userDOB")
export const GENDER = global?.localStorage?.getItem("userGender")
export const USER_FIRST_NAME = global?.localStorage?.getItem("userFirstName")
export const USER_LAST_NAME = global?.localStorage?.getItem("userLastName")
export const USER_EMAIL = global?.localStorage?.getItem("userEmail")
export const USER_PHONE_NUMBER = global?.localStorage?.getItem("userPhoneNumber")
export const USER_COUNTRY_CODE = global?.localStorage?.getItem("userCountryCode")
export const USER_TYPE = global?.window?.localStorage?.getItem("userType")
export const EPICURE_ID = global?.window?.localStorage?.getItem("epicureMemberID")
export const EPICURE_TIER = global?.window?.localStorage?.getItem("epicureMemberTier")
export const USER_TIRE = global?.window?.localStorage?.getItem("userTier")
export const CHAMBERS_ID = global?.window?.localStorage?.getItem("chambersMemberID")
export const CHAMBERS_TIER = global?.window?.localStorage?.getItem("chambersMemberTier")
export const IS_EMAIL_VERIFIED = global?.window?.localStorage?.getItem("userEmailVerified")
export const ACCESS_TOKEN = global?.window?.localStorage?.getItem("accessToken")
export const CUSTOMER_HASH = global?.window?.localStorage?.getItem("customerHash")
export const REFRESH_TOKEN = global?.window?.localStorage?.getItem("refreshToken")
export const LOGIN_JOURNEY_TYPE = global?.window?.localStorage?.getItem("loginJourneyType")
export const EPICURE_START_DATE = global?.window?.localStorage?.getItem("epicureMemberStartDate")
export const EPICURE_END_DATE = global?.window?.localStorage?.getItem("epicureMemberEndDate")
export const LOGIN_METHOD = global?.window?.localStorage?.getItem("loginJourneyType")
export const USER_NATIONALITY = global?.window?.localStorage?.getItem("userNationality")
export const isUserLoggedIn = global?.localStorage?.getItem("customerHash")
export const HOTEL_JOURNEY_TYPE = global?.localStorage?.getItem("hotelJourneyPageType")
export const ACTIVE_TAB_NAME = global?.localStorage?.getItem("activeTabName")
// Analytics constants
export const POWERED_BY_WIDGET = "Sanity"
export const PAGE_LANG = "en-in"
export const AFFILIATION = "Taj"
export const EPICURE = "Epicure"
export const EPICURE_MEMBERSHIP = "Epicure Membership"
export const MEMBERSHIP = "Membership"
export const GIFT_CARD = "Gift Card"
export const GIFT_CARD_PURCHASE = "GiftCard purchase"
export const PURCHASE = "purchase"
export const BEGIN_CHECKOUT = "begin_checkout"
export const SELECT_ITEM = "select_item"
export const ENQUIRE_NOW_SUBMIT = "enquiry_form_submit"
export const ENQUIRE_NOW_CLICKED = "enquireNow_Clicked"
export const TAJ_HOTELS = "Tajhotels"
export const SIGNUP_WIDGET_TITLE = "LOGIN / JOIN"
export const SIGNUP_JOURNEY_TYPE = "SignIn"
export const NOT_LOGGEDIN = "Not LoggedIn"
export const LOGIN_TYPE = "LogIn"
export const SIGNUP = "SignUp"
export const widget_Type = "Card"
