import { triggerEvent } from "../../.."
import { getCookie } from "../../../../cookie"
import { AFFILIATION, GIFT_CARD } from "../../../constants"

export const handleGCReloadPurchase = (
  eventName: string,
  dataLayer: any,
  address: any,
  reloadGCResponse: any,
  reloadedGiftCard: any
) => {
  triggerEvent({
    action: eventName,
    params: {
      ...dataLayer,
      arrivalDate: "",
      departureDate: "",
      noOfAdults: "",
      noOfChild: "",
      noOfRooms: "",
      bookingType: "",
      bookingPaymentType: "",
      location: "",
      eventType: "",
      eventName: "",
      eventPlace: "",
      eventTicketsQty: "",
      eventDate: "",
      userPinCode: address?.pinCode ? address?.pinCode : "",
      userState: address?.state ? address?.state : "",
      userCity: address?.cityTown ? address?.cityTown : "",
      visitSource: "",
      brandName: AFFILIATION,
      datesToBook: "",
      giftCardCategory: reloadedGiftCard?.theme || "",
      giftCardType: "",
      giftCardValue: reloadGCResponse?.priceTotal || "",
      giftCardQuantity: reloadGCResponse?.giftCard?.length || "",
      offerName: "",
      offerCode: "",
      offerID: "",
      offerCategory: "",
      offerValidity: "",
      redemptionType: "",
      redemptionName: "",
      redemptionDescription: "",
      pointsType: "",
      pointstobeRedeemed: "",
      buttonLinkName: "",
      link_url: "",
      link_text: "",
      outbound: "true",
      clientId: getCookie("_ga")?.slice(6),
      ecommerce: {
        currency: "INR",
        transaction_id: reloadGCResponse?.purchaseOrderNo || "",
        value: reloadedGiftCard?.amount || "",
        tax: 0,
        payment_type: reloadGCResponse?.paymentMethod?.split("BY")?.[1] || "",
        payment_status: reloadGCResponse?.paymentMethod?.split("BY")?.[0] || "",
        giftcard_redeem_amount: "",
        nuecoins_redeem_amount: "",
        items: [
          {
            item_id: reloadedGiftCard?.sku || "",
            item_name: reloadedGiftCard?.theme || "",
            affiliation: AFFILIATION,
            index: 0,
            item_category: GIFT_CARD,
            item_category2: "",
            item_category3: "Reload",
            item_category4: "",
            item_list_id: "",
            item_list_name: "",
            price: reloadGCResponse?.priceTotal || "",
            quantity: reloadGCResponse?.giftCard?.length || "",
          },
        ],
      },
    },
  })
}
