export const EpicureFormInitialValues = {
  INITIAL_VALUES: {
    firstName: "",
    lastName: "",
    senderEmail: "",
    receiverMobile: "",
    address: "",
    gstNo: "",
    pinCode: "",
    addOnFirstName: "",
    addOnLastName: "",
    addOnEmail: "",
    addOnMobile: "",
  },
  INITIAL_STATES: {
    disableSalutation: false,
    disableFirstName: false,
    disableLastName: false,
    disableEmail: false,
    disablePhone: false,
    disableDob: false,
    disableAddress: false,
    disableCountry: false,
    disableState: false,
    disableCity: false,
    disablePinCode: false,
  },
  DEFAULT_VALUES: {
    country: "India",
    city: "",
    state: "",
    title: "",
    addOnTitle: "",
  },
  INITIAL_SELECT_STATE: {
    salutation: false,
    country: false,
    state: false,
    city: false,
    addOnSalutation: false,
  },
  INITIAL_ERRORS: {
    firstName: false,
    lastName: false,
    senderEmail: false,
    receiverMobile: false,
    address: false,
    gstNo: false,
    pinCode: false,
    addOnFirstName: false,
    addOnLastName: false,
    addOnEmail: false,
    addOnMobile: false,
  },
}
