export const ROUTES = {
  WITHOUTSEO_FOR_ROUTING: {
    MY_ACCOUNT: {
      OVERVIEW: "/my-account",
      BOOKING_DETAILS: "/my-account/booking-detail",
      CANCEL_BOOKING: "/my-account/cancel-booking",
      CHANGE_DATES: "/my-account/booking/change-dates",
      CHANGE_ROOMS: "/my-account/booking/change-rooms",
      CHANGE_ROOMS_DETAIL: "/my-account/booking-detail/change-rooms",
    },
    HOMEPAGE: "/homepage",
    BOOKING: {
      CART: "/bookings/landing-page",
      CONFIRMED_PAGE: "/booking/booking-confirmed",
      REVIEW_BOOKING_MODAL: "/booking/review-booking-room",
      MODIFY_CONFIRMED_PAGE: "/booking/modified-booking-confirmed",
    },
    GIFT_CARD: {
      RELOAD_CONFIRMATION: "/gift-card/reload-card",
      PURCHASE_SUCCESS: "/e-gift-card-confirmation",
    },
    LOYALTY: {
      LOYALTY_PURCHASE_CONFIRMATION: "/loyalty/epicure-membership-purchase",
    },
    SSO: {
      LOGIN: "/neupass-login",
    },
  },
  DESTINATIONS: "/en-in/destinations",
  HOMEPAGE: "/en-in/homepage",
  BOOKING: {
    CART: "/en-in/bookings/landing-page",
    CONFIRMED_PAGE: "/en-in/booking/booking-confirmed",
    REVIEW_BOOKING_MODAL: "/en-in/booking/review-booking-room",
    MODIFY_CONFIRMED_PAGE: "/en-in/booking/modified-booking-confirmed",
  },
  MY_ACCOUNT: {
    OVERVIEW: "/en-in/my-account",
    BOOKING_DETAILS: "/en-in/my-account/booking-detail",
    CANCEL_BOOKING: "/en-in/my-account/cancel-booking",
    CHANGE_DATES: "/en-in/my-account/booking/change-dates",
    CHANGE_ROOMS: "/en-in/my-account/booking/change-rooms",
    CHANGE_ROOMS_DETAIL: "/en-in/my-account/booking-detail/change-rooms",
  },
  LOYALTY: {
    LOYALTY_PURCHASE_CONFIRMATION: "/en-in/loyalty/epicure-membership-purchase",
  },
  GIFT_CARD: {
    RELOAD_CONFIRMATION: "/en-in/gift-card/reload-card",
    PURCHASE_SUCCESS: "/en-in/e-gift-card-confirmation",
  },
  PRIVACY_POLICY: "/en-in/privacy-policy",
  TERMS_OF_USE: "/en-in/about-us/terms-of-use",
  COOKIES_POLICY: "/en-in/cookies-policy",
  DATA_PROTECTION: "/en-in/data-protection",
  ACCESSIBILITY: "/en-in/about-us/accessibility",
  FAQ_PAGE: "/en-in/faq-page",
  FIND_YOUR_BOOKING: "/en-in/my-account/find-your-booking",
  CHAMBERS_FAQ: "/en-in/chambers-faq-page",
  TAJ_CLUB_FAQ: "/en-in/taj-club-faq-page",
  NEU_PASS_FAQ: "/en-in/neupass-faq-page",
  EPICURE_FAQ: "/en-in/epicure-faq-page",
  GIFTCARD_FAQ: "/en-in/faq-gift-card",
  NON_LOGGED_IN_BOOKING_DETAILS: "/en-in/my-account/booking-detail-test",
  CC_TERMS_AND_CONDITIONS: "/en-in/coupon-code/terms-of-use",
}
